@SCHEME = http
@HOST = localhost
@PORT = 8090

### GET api/user/all
GET {{SCHEME}}://{{HOST}}:{{PORT}}/api/user/all

### POST api/user
POST {{SCHEME}}://{{HOST}}:{{PORT}}/api/user

{
	"name": "haquocdat",
	"email": "haquocdat@gmail.com",
	"password": "12345678"
}
