name: Check

on:
  pull_request:
  push:

env:
  TOOLCHAIN_VERSION: 1.89.0
  COMPONENTS: rustfmt, clippy

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.TOOLCHAIN_VERSION }}
          components: ${{ env.COMPONENTS }}

      - name: Binstall
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-expand,cargo-watch,cargo-edit,cargo-nextest,cargo-llvm-lines,cargo-bloat,cargo-outdated,cargo-update,cargo-deny,cargo-geiger,cargo-tarpaulin,flamegraph,cargo-udeps,cargo-zigbuild,just,cargo-make,cargo-px,cargo-dist

      - name: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/sccache
            ~/.cargo/bin
            ~/.cargo/binstall
            ~/.cargo/git
            ~/.cargo/registry
          key: rust-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}-${{ github.run_id }}
          restore-keys: |
            rust-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}-

      - name: sccache statistics
        if: always()
        run: sccache --show-stats || true
