name: Lint

on:
  pull_request:
  push:

env:
  TOOLCHAIN_VERSION: 1.89.0
  COMPONENTS: rustfmt, clippy

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.TOOLCHAIN_VERSION }}
          components: ${{ env.COMPONENTS }}

      - name: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/sccache
            ~/.cargo/bin
            ~/.cargo/binstall
            ~/.cargo/git
            ~/.cargo/registry
          key: rust-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}-${{ github.run_id }}
          restore-keys: |
            rust-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}-

      - name: Run rustfmt
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
